/charuco_node:
  ros__parameters:
    marker_size: 0.0225
    charuco_dictionary_id: DICT_5X5_250
    image_topic: /camera/color/image_raw
    camera_info_topic: /camera/color/camera_info
    # Visualization settings
    enable_visualization: true
    visualization_topic: /charuco/image_detections
